# Generated by Django 5.2.8 on 2025-11-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
