# Generated by Django 4.2.23 on 2025-09-21 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overall_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, choices=[('very_bad', 'Very Bad'), ('bad', 'Bad'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(blank=True, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('instance_summary', models.TextField(blank=True, null=True)),
                ('date_of_the_report', models.DateTimeField(auto_now_add=True)),
                ('address_of_the_doctor', models.TextField(blank=True, null=True)),
                ('name_of_the_doctor', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='reports.report')),
            ],
        ),
    ]
