# Generated by Django 4.2.23 on 2025-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinstance',
            name='youtube_videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
