# Generated by Django 4.2.23 on 2025-11-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDeets', '0003_alter_userdeets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeets',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
